### ISSUE TITLE
The syn crate feature "full" should be enabled

### ISSUE THREAD

**Issue by vinhig** [zakcutner/rumpsteak#2]
As of https://docs.rs/syn/1.0.0/syn/struct.ItemMod.html, (the version of the crate "syn" that you're currently using), you should enable the "full" feature to allow `macros/src/session.rs` to be properly compiled.

I don't understand how was it compiling before, but on my MacOS with the latest stable toolchain, I get:

```
 --> macros/src/session.rs:6:33
  |
6 |     GenericParam, Ident, Index, Item, ItemEnum, ItemStruct, ItemType, PathArguments, Result, Type,
  |                                 ^^^^  ^^^^^^^^  ^^^^^^^^^^  ^^^^^^^^ no `ItemType` in the root
  |                                 |     |         |
  |                                 |     |         no `ItemStruct` in the root
  |                                 |     no `ItemEnum` in the root
  |                                 no `Item` in the root
```

which is expected. On `macros/Cargo.toml`, line 19, the fix is now `syn = { version = "1.0", features = ["extra-traits", "full"] }`.

I feel ashamed to do a pull request for a single line, or maybe my brain is too smooth to understand what happened.

Anyway, have a great day!

**Comment by Bromind** [comment]
Hi, 
thanks for the notification. It should be fixed now. I don't know why it didn't show up before either.

Could you confirm it works on your side as well, before I close the issue?

Have a nice day !

**Comment by vinhig** [comment]
Yup, can confirm it compiles with your latest commit. Everything's good.

Have a nice day, and keep up the good work!
